require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/*.gemspec'
    - '**/Rakefile'
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'

Rails:
  Enabled: true

Style/Encoding:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/RaiseArgs:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/CaseIndentation:
  IndentWhenRelativeTo: end
  SupportedStyles:
    - case
    - end
  IndentOneStep: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Semicolon:
  Exclude:
    - '**/*_spec.rb'

Style/RescueModifier:
  Exclude:
    - '**/*_spec.rb'

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/ClassAndModuleChildren:
  Exclude:
   - 'config/application.rb'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 35

Rails/HasAndBelongsToMany:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
   - 'spec/views/**/*'

# the following cop has been temporary disabled until rubocop-rspec has been updated.
# Check for updates here: https://github.com/nevir/rubocop-rspec
# latest release: RuboCop RSpec v1.3.1 on Sep 4, 2015
RSpec/FilePath:
  Enabled: false
