development:
  adapter: postgresql
  encoding: utf8
  database: mammooc_development
  pool: 5
  username: sebastian
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: mammooc_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: mammooc
  # Check /etc/systemd/system/mammooc-sidekiq.service for sidekiq concurrency
  pool: 20
  username:
  password:
